#!/bin/sh

interface=$1 status=$2
if [ "$CONNECTION_ID" = "SSID NAME" ]; then
  case $status in
    up)
      ;;
    down)
      ;;
  esac
fi

if ! [ "$CONNECTION_ID" = "SSID NAME" ]; then
  case $status in
    up)
      ;;
    down)
      ;;
  esac
fi