[main]
color-tsharks = ['/usr/bin/tshark']
dark-mode = true
last-used-tshark = '/usr/bin/tshark'
packet-colors = true
recent-filters = ['udp.stream eq 85']
validated-tsharks = ['/usr/bin/tshark', '/usr/local/bin/tshark']

